config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :find_flat, only: [:show, :edit, :update, :destroy]

  def index
    @flats = Flat.all
  end
        
  def new
    @flat = Flat.new
  end
        
  def show; end
        
  def create
    @flat = Flat.new(flat_params)
      if @flat.save
        redirect_to flat_path(@flat), notice: 'Flat was successfully created'
      else
        render :new
      end
    end
        
  def edit; end
        
  def update
    @flat.update(flat_params)
    redirect_to flat_path(@flat)
  end
        
  def destroy
    @flat.destroy
    redirect_to flats_path
  end
        
  private
        
  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end
  
  def find_flat
    @flat = Flat.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/edit.html.erb
<%= simple_form_for @flat do |f| %>
  <%= f.input :name %>
  <%# <%= f.text_field :name %>
  <%= f.input :address %>
  <%# <%= f.text_field :address %>
  <%= f.input :description %>
  <%# <%= f.text_field :category %>
  <%= f.input :price_per_night %>
  <%# <%= f.text_field :phone_number %>
  <%= f.input :number_of_guests %>
  <%= f.submit %>
<% end %>

app/views/flats/index.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="col-12">
      <h1>All our Flats</h1>
    </div>
  </div>

  <div class="row">
    <div class="col">
        <p>All <%= @flats.count%> flats.</p>
    </div>
  </div>

  <div class="row">
    <% @flats.each do |flat| %>
      <div class="col-4">
        <div class="flat-card">
          <%# <div class="flat-card-image" style="background-image: url('https://images.unsplash.com/photo-1494526585095-c41746248156?w=1200')"></div> %>
          <div class="flat-card-content">
            <div class="flat-card-title">
              <h4><%= flat.name %></h4>
            </div>
            <p><%= flat.address %></p>
            <div class="flex">
              <div class="flex">
                <i class="fas fa-user-friends"></i>  <span><%= flat.number_of_guests %></span>
              </div>
              <div class="flex ml-3">
                <i class="fas fa-euro-sign"></i> <%= flat.price_per_night %>
              </div>
            </div>
          </div>
          <div class="flat-card-actions">
            <%= link_to "More info", flat_path(flat) %>
            <%# <a href="/flats/5696">More info</a> %>
            <%= link_to 'Edit', edit_flat_path(flat), class: 'ml-3 text-warning' %>
            <%# <a class="ms-3 text-warning" href="/flats/5696/edit">Edit</a> %>
            <%= link_to "Remove", flat_path(flat), method: :delete, data: { confirm: 'Are you sure?' }, class: 'ml-3 text-danger' %>
            <%# <a data-confirm="Are you sure?" class="ml-3 text-danger" rel="nofollow" data-method="delete" href="/flats/:id">Remove</a> %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

   
   
  <%# <% @flats.each do |flat| %>
    <%# <h2><%= flat.name</h2> %>
    <%# <p><%= flat.address<br> %>
      <%# guests: <%= flat.number_of_guests %>  
      <%# price per night: <%= flat.price_per_night %>
      <%# </p> %>
    <%# <%= link_to "More info", flat_path(flat) %>
    <%# <%= link_to "Edit", edit_flat_path(flat) %>
    <%# <%= link_to "Remove", flat_path(flat), method: :delete, data: { confirm: 'Are you sure?' } %>
    <%# <br> %>
    <%# <br> %>
  <%# <% end %>
<%# </div> %>


app/views/flats/new.html.erb
<%= simple_form_for @flat do |f| %>
  <%= f.input :name %>
  <%# <%= f.text_field :name %>
  <%= f.input :address %>
  <%# <%= f.text_field :address %>
  <%= f.input :description %>
  <%# <%= f.text_field :category %>
  <%= f.input :price_per_night %>
  <%# <%= f.text_field :phone_number %>
  <%= f.input :number_of_guests %>
  <%= f.submit %>
<% end %>

app/views/flats/show.html.erb
<div class="flat-container-content">
  <div class="flat-basic">
    <h1><%= @flat.name %></h1>
    <p><%= @flat.address %></p>
  </div>
  <br>
  <div class="flat-more">
    <h2>A bit more about us......</h2>
    <p><%= @flat.description %></p>
  </div>
  <br>
  <div class="flat-details">
    <h2>Details</h2>
      <div class="flex">
        <i class="fas fa-euro-sign"></i><p><%= @flat.price_per_night %></p>
      </div>
      <div class="flex">
        <i class="fas fa-user-friends"></i>  <p>guests: <%= @flat.number_of_guests %></p>
      </div>
  </div>
  <div class="flat-action">
    <%= link_to "Back to flat list", flats_path %>
    <%= link_to "Edit", edit_flat_path(@flat), class: 'ml-3 text-warning' %>
    <%= link_to "Remove", flat_path(@flat), method: :delete, data: { confirm: 'Are you sure?' }, class: 'ml-3 text-danger' %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar">
      <a class="navbar-brand" href="#">Simple Airbnb</a>
      <%# <div class="ml-auto flex"> %>
          <%# <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" name="query" type="search" placeholder="Search" aria-label="Search" value="">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form> %>
      <a class="btn btn-outline-primary my-2 my-sm-0 ml-2" href="/flats/new">Add Flat</a>
      <%# </div> %>
    </nav>
    <%= yield %>
  </body>
</html>